version: "3"

volumes:
  local_postgres_data: {}
  local_nsc_data: {}
services:
  django: &django # enables use of pdb
    hostname: django
    stdin_open: true
    tty: true
    build:
      context: ../
      dockerfile: ./docker/django.Dockerfile
    image: django_nats_nkeys
    container_name: django_nats_nkeys
    depends_on:
      - postgres
    volumes:
      - ../:/workspace:z
      - local_nsc_data:/var/lib/nats/nsc:z
    ports:
      - "8000:8000"
    env_file:
      - test.env
    environment:
      NKEYS_PATH: /var/lib/nats/nsc/keys
      NSC_HOME: /var/lib/nats/nsc
      NSC_STORE: /var/lib/nats/nsc/stores
    command:
      - ./start
  postgres:
    hostname: postgres
    image: postgres:14
    container_name: django_nats_nkeys_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:z
    env_file:
      - test.env
    ports:
      - "5432:5432"
  nats:
    hostname: nats
    image: nats:2.8-alpine
    container_name: django_nats_nkeys_nats
    volumes:
      - ../.nats/:/etc/nats
    command:
      - -c
      - /etc/nats/nats-server.conf
      - --name
      - localnats
    ports:
      - "4222:4222"
