version: "3"

volumes:
  local_django_nats_nkeys_postgres_data: {}
services:
  django: &django # enables use of pdb
    hostname: django
    stdin_open: true
    tty: true
    build:
      context: ../
      dockerfile: ./docker/django.Dockerfile
    image: django_nats_nkeys
    container_name: django_nats_nkeys
    depends_on:
      - postgres
      - nats
    volumes:
      - ../:/workspace:z
    ports:
      - "8801:8000"
    env_file:
      - test.env
    environment:
      NKEYS_PATH: /workspace/.nats/keys
      NSC_HOME: /workspace/.nats/config
      NSC_STORE: /workspace/.nats/stores
    command:
      - ./start
  postgres:
    hostname: postgres
    image: postgres:14
    container_name: django_nats_nkeys_postgres
    volumes:
      - local_django_nats_nkeys_postgres_data:/var/lib/postgresql/data:z
    env_file:
      - test.env
    ports:
      - "5433:5432"
  nats:
    hostname: nats
    container_name: django_nats_nkeys_nats
    build:
      dockerfile: nats.Dockerfile
      context: .
    volumes:
      - ../.nats/:/etc/nats
    command:
      - -c
      - /etc/nats/nats-server.conf
      - --name
      - localnats
    ports:
      - "4223:4223"
