# Generated by Django 3.2.7 on 2022-11-04 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_nats_nkeys", "0006_natsrobotapp_unique_app_name_per_robot_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="natsorganization",
            name="jetstream_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Enable JetStream for all users/apps belonging to NatsOrganization account",
            ),
        ),
        migrations.AddField(
            model_name="natsorganization",
            name="jetstream_max_consumers",
            field=models.PositiveIntegerField(
                default=10,
                help_text="JetStream max number of consumers (shared across all users/apps beloning to NatsOrganization account)",
            ),
        ),
        migrations.AddField(
            model_name="natsorganization",
            name="jetstream_max_file",
            field=models.CharField(
                default="5M",
                help_text="JetStream file resource limits (shared across all users/apps beloning to NatsOrganization account)",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="natsorganization",
            name="jetstream_max_mem",
            field=models.CharField(
                default="1M",
                help_text="JetStream memory resource limits (shared across all users/apps beloning to NatsOrganization account)",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="natsorganization",
            name="jetstream_max_streams",
            field=models.PositiveIntegerField(
                default=10,
                help_text="JetStream max number of streams (shared across all users/apps beloning to NatsOrganization account)",
            ),
        ),
    ]
