# Generated by Django 3.2.7 on 2022-11-05 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_nats_nkeys", "0007_auto_20221104_2311"),
    ]

    operations = [
        migrations.AddField(
            model_name="natsorganizationapp",
            name="bearer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="natsorganizationuser",
            name="bearer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="natsrobotapp",
            name="bearer",
            field=models.BooleanField(default=False),
        ),
    ]
